### ISSUE TITLE
Better error message for read_csv when NULL headers are found

### ISSUE THREAD

**Issue by jaychia** [Eventual-Inc/Daft#324] opened 2022-11-10 18:43 UTC
**Describe the bug**
We should throw a more informative error that tells users to specify headers explicitly when parsing a CSV with no headers, and some of the cells in the first row are NULL.

**Comment by xcharleslin** [comment] 2022-11-29 03:14
I'm having trouble reproducing this, both with csvs of the form

```csv
,
```

```csv
a,b,,d
```

and calls of the form

```python
DataFrame.read_csv("test.csv")
DataFrame.read_csv("test.csv", has_headers=False)
```

The only error I could get to raise was with the csv with just commas, which gives
```python
  File "<stdin>", line 1, in <module>
  File "/home/orbit/workspace/daft/daft/dataframe/dataframe.py", line 344, in read_csv
    schema = _sample_with_pyarrow(
  File "/home/orbit/workspace/daft/daft/dataframe/dataframe.py", line 56, in _sample_with_pyarrow
    schema = ExpressionList(
  File "/home/orbit/workspace/daft/daft/logical/schema.py", line 22, in __init__
    raise ValueError(f"duplicate name found {e_name}")
ValueError: duplicate name found 
```

This may actually be the correct error to raise here, since there are duplicate empty strings in the header. Closing for now after discussing with @jaychia .

Having an option for more "magical" csv parsing might be something we consider in the future.

**Closed by xcharleslin** 2022-11-29 03:14 UTC
Labels: good first issue
