### ISSUE TITLE
NameError: name '_X5ix_PYCCOLO_TRACING_ENABLED' is not defined with @polars_udf

### ISSUE THREAD

**Issue by xdssio** [Eventual-Inc/Daft#514] opened 2023-01-26 15:41 UTC
**Describe the bug**
When using ray_runner and using polars_udf, we get an error.

**To Reproduce**
```
import daft
import polars as pl

daft.context.set_runner_ray()

df = daft.DataFrame.read_csv('~/development/datasets/titanic.csv')

@daft.polars_udf(return_type=int)
def test(pclass: pl.Series):
    return pclass

df.with_column('test', test(df['pclass'])).show()

>>>
      9 @daft.polars_udf(return_type=int)
     10 def test(pclass: pl.Series):
     11     return pclass
---> 13 df.with_column('test', test(df['pclass'])).show()

File ~/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/dataframe/dataframe.py:189, in DataFrame.show(self, n)
    186 if n is not None:
    187     df = df.limit(n)
--> 189 df.collect(num_preview_rows=n)
    190 result = df._result
    191 assert result is not None

File ~/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/dataframe/dataframe.py:1078, in DataFrame.collect(self, num_preview_rows)
   1075 self._materialize_results()
   1077 assert self._result is not None
-> 1078 dataframe_len = len(self._result)
   1079 requested_rows = dataframe_len if num_preview_rows is None else num_preview_rows
   1081 # Build a DataFramePreview and cache it if we need to

File ~/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/runners/ray_runner.py:130, in RayPartitionSet.__len__(self)
    129 def __len__(self) -> int:
--> 130     return sum(self.len_of_partitions())

File ~/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/runners/ray_runner.py:139, in RayPartitionSet.len_of_partitions(self)
    135 @ray.remote
    136 def remote_len(p: vPartition) -> int:
    137     return len(p)
--> 139 result: list[int] = ray.get([remote_len.remote(self._partitions[pid]) for pid in partition_ids])
    140 return result

File ~/development/daft_notebooks/.venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:105, in client_mode_hook.<locals>.wrapper(*args, **kwargs)
    103     if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104         return getattr(ray, func.__name__)(*args, **kwargs)
--> 105 return func(*args, **kwargs)

File ~/development/daft_notebooks/.venv/lib/python3.9/site-packages/ray/_private/worker.py:2309, in get(object_refs, timeout)
   2307     worker.core_worker.dump_object_store_memory_usage()
   2308 if isinstance(value, RayTaskError):
-> 2309     raise value.as_instanceof_cause()
   2310 else:
   2311     raise value

RayTaskError(NameError): ray::remote_len() (pid=72500, ip=127.0.0.1)
  At least one of the input arguments for this task could not be computed:
ray.exceptions.RayTaskError: ray::_ray_partition_single_part_runner() (pid=72500, ip=127.0.0.1)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/runners/ray_runner.py", line 232, in _ray_partition_single_part_runner
    return op_runner.run_node_list_single_partition(input_partitions, nodes=nodes, partition_id=partition_id)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/execution/logical_op_runners.py", line 70, in run_node_list_single_partition
    output = self.run_single_node(inputs=part_set, node=node, partition_id=partition_id)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/execution/logical_op_runners.py", line 80, in run_single_node
    return self._handle_projection(inputs, node, partition_id=partition_id)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/execution/logical_op_runners.py", line 169, in _handle_projection
    return prev_partition.eval_expression_list(proj._projection)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/runners/partitioning.py", line 232, in eval_expression_list
    tile_list = [self.eval_expression(e) for e in exprs]
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/runners/partitioning.py", line 232, in <listcomp>
    tile_list = [self.eval_expression(e) for e in exprs]
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/runners/partitioning.py", line 224, in eval_expression
    result = exec.eval(expr, required_blocks)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/expressions.py", line 91, in eval
    result = self.eval(expr._expr, operands)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/expressions.py", line 111, in eval
    results = expr._func(*eval_args, **eval_kwargs)
  File "/Users/yonatanalexander/development/daft_notebooks/.venv/lib/python3.9/site-packages/daft/udf.py", line 202, in prepost_process_data_block_func
    results = initialized_func(*converted_args, **converted_kwargs)
  File "/var/folders/gl/cklpy5415rzd6vb8y29rccpr0000gn/T/ipykernel_72470/640872067.py", line 10, in test
NameError: name '_X5ix_PYCCOLO_TRACING_ENABLED' is not defined
```

**Expected behavior**
Same results for py_runner.    
If you remove the line `daft.context.set_runner_ray()`, it works.

**Desktop 
 - OS: OSX, M1 
 - Version getdaft==0.0.20

**Comment by jaychia** [comment] 2023-01-26 20:10
I am unable to reproduce this on my M2 Macbook and getdaft==0.0.20 :(

Can you also please send your full list of dependencies with `pip freeze`? I will try reproducing with the same version of iPython and Ray.

Separately, are you running this on any sort of emulation/virtual machine?

**Comment by xdssio** [comment] 2023-01-27 11:45
```
aiohttp==3.8.3
aiosignal==1.3.1
anyio==3.6.2
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
astunparse==1.6.3
async-timeout==4.0.2
attrs==22.2.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.1
black==22.12.0
bleach==6.0.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
comm==0.1.2
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.6
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
filelock==3.9.0
fqdn==1.5.1
frozenlist==1.3.3
fsspec==2023.1.0
getdaft==0.0.20
grpcio==1.51.1
idna==3.4
importlib-metadata==6.0.0
ipyflow==0.0.156
ipyflow-core==0.0.156
ipykernel==6.20.2
ipython==8.8.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
joblib==1.2.0
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-events==0.6.3
jupyter_client==7.4.9
jupyter_core==5.1.5
jupyter_server==2.1.0
jupyter_server_terminals==0.4.4
jupyterlab==3.5.3
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
jupyterlab_server==2.19.0
lightgbm==3.3.5
lightgbm-ray==0.1.8
loguru==0.6.0
MarkupSafe==2.1.2
matplotlib-inline==0.1.6
mistune==2.0.4
msgpack==1.0.4
multidict==6.0.4
mypy-extensions==0.4.3
nbclassic==0.4.8
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.5
packaging==23.0
pandas==1.5.3
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.11.0
pexpect==4.8.0
pickleshare==0.7.5
platformdirs==2.6.2
polars==0.15.17
prometheus-client==0.16.0
prompt-toolkit==3.0.36
protobuf==3.20.1
psutil==5.9.4
ptyprocess==0.7.0
pure-eval==0.2.2
pyarrow==10.0.1
pyccolo==0.0.45
pycparser==2.21
pydot==1.4.2
Pygments==2.14.0
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.7.1
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
ray==2.2.0
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
scikit-learn==1.2.1
scipy==1.10.0
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
tabulate==0.9.0
tensorboardX==2.5.1
terminado==0.17.1
threadpoolctl==3.1.0
tinycss2==1.2.1
tomli==2.0.1
tornado==6.2
traitlets==5.8.1
typing_extensions==4.4.0
uri-template==1.2.0
urllib3==1.26.14
virtualenv==20.17.1
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.0
widgetsnbextension==4.0.5
wrapt==1.14.1
xgboost==1.7.3
xgboost-ray==0.1.13
yarl==1.8.2
zipp==3.11.0
```

**Comment by jaychia** [comment] 2023-02-10 17:22
Closing this - unable to reproduce! Please re-open and comment if this continues to be an issue.

**Comment by jaychia** [comment] 2023-02-10 17:23
For future readers, a workaround seems to be to just set `_X5ix_PYCCOLO_TRACING_ENABLED = False` in your notebook cell.

**Closed by jaychia** 2023-02-10 17:22 UTC
