### ISSUE TITLE
M1 Mac installation issue -ImportError: dlopen

### ISSUE THREAD

**Issue by xdssio** [Eventual-Inc/Daft#513] opened 2023-01-26 10:28 UTC
**Describe the bug**
After installation, import of daft crashes.

**To Reproduce**
1. Install from pip
2. `import daft` 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".venv/lib/python3.9/site-packages/daft/__init__.py", line 19, in <module>
    from daft.daft import build_type as _build_type
ImportError: dlopen(../.venv/lib/python3.9/site-packages/daft/daft.abi3.so, 0x0002): tried: '.venv/lib/python3.9/site-packages/daft/daft.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/.venv/lib/python3.9/site-packages/daft/daft.abi3.so' (no such file), '.venv/lib/python3.9/site-packages/daft/daft.abi3.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

**Expected behavior**
```
import daft
```

**System**
 - OSX, M1 mac.
 - Version: getdaft==0.0.21
 (tried installing from master from git too)

**Workaround**
Version 0.0.20 works.

**Comment by jaychia** [comment] 2023-01-26 19:45
Thanks for reporting this @xdssio!

I just did a `pip install getdaft` on an arm64 machine (M2 Mac) and it correctly installed the arm64 wheel for me. The issue that you are seeing is likely caused by pip installing the wrong x86 wheel.

Can you try installing this and see if it works? This explicitly points to the wheel that we have built/hosted in PyPi.

```
pip install https://files.pythonhosted.org/packages/96/c2/a19bc06c70569eb47c1f9b32ffd4a7e20fdbca75c67951e9fea8eff5af5f/getdaft-0.0.21-cp37-abi3-macosx_11_0_arm64.whl
```

If this works for you, then we can dig further into why your pip isn't resolving to the correct wheel.

**Comment by jaychia** [comment] 2023-01-26 19:56
Also, the ordering of your error message `(have 'arm64', need 'x86_64')` seems odd, since you are on a Mac M1 it should say `need arm64` instead I believe.

Are you running Python in some kind of virtual machine or Docker environment?

**Closed** 2023-02-10 17:23 UTC
