### ISSUE TITLE
how to read a csv with a variable number of columns

### ISSUE THREAD

**Issue by djouallah** [Eventual-Inc/Daft#2305] opened 2024-05-26 11:20 UTC
I am tying to read a malformed csv, basically the number of columns in variable
```
import daft
from daft import DataType
schema={
			'I': DataType.string(),'UNIT': DataType.string(),'XX': DataType.string(),'VERSION': DataType.string(),'SETTLEMENTDATE': DataType.string(),'RUNNO': DataType.string(),
			'DUID': DataType.string(),'INTERVENTION': DataType.string(),'DISPATCHMODE': DataType.string(),'AGCSTATUS': DataType.string(),'INITIALMW': DataType.string(),
			'TOTALCLEARED': DataType.string(),'RAMPDOWNRATE': DataType.string(),'RAMPUPRATE': DataType.string(),'LOWER5MIN': DataType.string(),
			'LOWER60SEC': DataType.string(),'LOWER6SEC': DataType.string(),'RAISE5MIN': DataType.string(),'RAISE60SEC': DataType.string(),
			'RAISE6SEC': DataType.string(),'MARGINAL5MINVALUE': DataType.string(),'MARGINAL60SECVALUE': DataType.string(),
			'MARGINAL6SECVALUE': DataType.string(),'MARGINALVALUE': DataType.string(),'VIOLATION5MINDEGREE': DataType.string(),
			'VIOLATION60SECDEGREE': DataType.string(),'VIOLATION6SECDEGREE': DataType.string(),'VIOLATIONDEGREE': DataType.string(),
			'LOWERREG': DataType.string(),'RAISEREG': DataType.string(),'AVAILABILITY': DataType.string(),'RAISE6SECFLAGS': DataType.string(),
			'RAISE60SECFLAGS': DataType.string(),'RAISE5MINFLAGS': DataType.string(),'RAISEREGFLAGS': DataType.string(),
			'LOWER6SECFLAGS': DataType.string(),'LOWER60SECFLAGS': DataType.string(),'LOWER5MINFLAGS': DataType.string(),
			'LOWERREGFLAGS': DataType.string(),'RAISEREGAVAILABILITY': DataType.string(),'RAISEREGENABLEMENTMAX': DataType.string(),
			'RAISEREGENABLEMENTMIN': DataType.string(),'LOWERREGAVAILABILITY': DataType.string(),'LOWERREGENABLEMENTMAX': DataType.string(),
			'LOWERREGENABLEMENTMIN': DataType.string(),'RAISE6SECACTUALAVAILABILITY': DataType.string(),
			'RAISE60SECACTUALAVAILABILITY': DataType.string(),'RAISE5MINACTUALAVAILABILITY': DataType.string(),
			'RAISEREGACTUALAVAILABILITY': DataType.string(),'LOWER6SECACTUALAVAILABILITY': DataType.string(),
			'LOWER60SECACTUALAVAILABILITY': DataType.string(),'LOWER5MINACTUALAVAILABILITY': DataType.string(),'LOWERREGACTUALAVAILABILITY': DataType.string()}
df = daft.read_csv(files_to_upload_full_Path,schema_hints=schema)
```
DaftCoreException                         Traceback (most recent call last)
[<ipython-input-26-c5f7e824ef2f>](https://localhost:8080/#) in <cell line: 3>()
      1 import daft
      2 from daft import DataType
----> 3 df = daft.read_csv(files_to_upload_full_Path,has_headers=False)

    [... skipping hidden 2 frame]

1 frames
[/usr/local/lib/python3.10/dist-packages/daft/io/common.py](https://localhost:8080/#) in get_tabular_files_scan(path, schema_hints, file_format_config, storage_config)
     36         raise NotImplementedError(f"get_tabular_files_scan cannot construct ScanOperatorHandle for input: {path}")
     37 
---> 38     scan_op = ScanOperatorHandle.glob_scan(
     39         paths,
     40         file_format_config,

DaftCoreException: DaftError::ArrowError External error: CSV error: record 1 (line: 1, byte: 86): found record with 25 fields, but the previous record has 10 fields

an example of the file  :  https://nemweb.com.au/Reports/Current/Daily_Reports/PUBLIC_DAILY_202405230000_20240524040504.zip

**Comment by jaychia** [comment] 2024-05-27 07:39
Hi @djouallah!

I just looked through your file, it seems like a pretty horribly malformed CSV with several columns that do not match the provided 25 column schema.

What is the intended behavior for rows that do not match the number of columns provided by the schema? I'm guessing the two main intended behaviors are to skip the row, or throw an error (which is the current behavior).

**Comment by djouallah** [comment] 2024-05-27 07:55
Fill with blank or skip

**Comment by colin-ho** [comment] 2024-06-18 20:07
Hi @djouallah ! The fix for this is in the latest release, you can see an example `read_csv` call here: https://github.com/Eventual-Inc/Daft/pull/2326 for the example file you provided

**Closed by colin-ho** 2024-06-18 20:07 UTC
